# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "tio-boot-admin-backend"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[[vm]]
  cpu_kind = "performance"
  cpus = 1
  memory_mb = 2048

[http_service]
  internal_port = 8100
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0