# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "tio-boot-admin-backend"
primary_region = 'sjc'

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[http_service]
  internal_port = 8100
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1