package nexus.io.tio.boot.admin.dto;

import nexus.io.tio.boot.admin.dto.base.BaseTioLlmUsage;

/**
 * Generated by java-db.
 */
public class TioLlmUsage extends BaseTioLlmUsage<TioLlmUsage> {
  private static final long serialVersionUID = 1L;
  public static final TioLlmUsage dao = new TioLlmUsage().dao();
  /**
   * 
   */
  public static final String tableName = "tio_llm_usage";
  public static final String primaryKey = "id";
  // java.lang.Long
  public static final String id = "id";
  // java.lang.Long
  public static final String groupId = "group_id";
  // java.lang.String
  public static final String groupName = "group_name";
  // java.lang.Long
  public static final String taskId = "task_id";
  // java.lang.String
  public static final String taskName = "task_name";
  // java.lang.String
  public static final String model = "model";
  // java.lang.String
  public static final String systemPrompt = "system_prompt";
  // java.lang.String
  public static final String messages = "messages";
  // java.lang.String
  public static final String content = "content";
  // java.lang.String
  public static final String usage = "usage";
  // java.lang.String
  public static final String provider = "provider";
  // java.lang.String
  public static final String apiKey = "api_key";
  // java.lang.Long
  public static final String elapsed = "elapsed";
  // java.lang.Integer
  public static final String status = "status";
  // java.lang.String
  public static final String creator = "creator";
  // java.util.Date
  public static final String createTime = "create_time";
  // java.lang.String
  public static final String updater = "updater";
  // java.util.Date
  public static final String updateTime = "update_time";
  // java.lang.Integer
  public static final String deleted = "deleted";
  // java.lang.Long
  public static final String tenantId = "tenant_id";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}
