package com.litongjava.tio.boot.admin.dto;



import com.litongjava.tio.boot.admin.dto.base.BaseTioLlmGenerateFailed;

/**
 * Generated by java-db.
 */
public class TioLlmGenerateFailed extends BaseTioLlmGenerateFailed<TioLlmGenerateFailed> {
  private static final long serialVersionUID = 1L;
	public static final TioLlmGenerateFailed dao = new TioLlmGenerateFailed().dao();
	/**
	 * 
	 */
  public static final String tableName = "tio_llm_generate_failed";
  public static final String primaryKey = "id";
  //java.lang.Long 
  public static final String id = "id";
  //java.lang.Long 
  public static final String groupId = "group_id";
  //java.lang.String 
  public static final String groupName = "group_name";
  //java.lang.Long 
  public static final String taskId = "task_id";
  //java.lang.String 
  public static final String taskName = "task_name";
  //java.lang.String 
  public static final String provider = "provider";
  //java.lang.String 
  public static final String requestUrl = "request_url";
  //java.lang.String 
  public static final String requestBody = "request_body";
  //java.lang.Integer 
  public static final String responseCode = "response_code";
  //java.lang.String 
  public static final String responseBody = "response_body";
  //java.lang.String 
  public static final String exception = "exception";
  //java.lang.String 
  public static final String apiKey = "api_key";
  //java.lang.Long 
  public static final String elapsed = "elapsed";
  //java.lang.Integer 
  public static final String status = "status";
  //java.lang.String 
  public static final String creator = "creator";
  //java.util.Date 
  public static final String createTime = "create_time";
  //java.lang.String 
  public static final String updater = "updater";
  //java.util.Date 
  public static final String updateTime = "update_time";
  //java.lang.Integer 
  public static final String deleted = "deleted";
  //java.lang.Long 
  public static final String tenantId = "tenant_id";

  @Override
  protected String _getPrimaryKey() {
    return primaryKey;
  }

  @Override
  protected String _getTableName() {
    return tableName;
  }
}

