package com.litongjava.tio.boot.admin.dto.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTioLlmUsage<M extends BaseTioLlmUsage<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setGroupId(java.lang.Long groupId) {
		set("group_id", groupId);
		return (M)this;
	}
	
	public java.lang.Long getGroupId() {
		return getLong("group_id");
	}
	
	public M setGroupName(java.lang.String groupName) {
		set("group_name", groupName);
		return (M)this;
	}
	
	public java.lang.String getGroupName() {
		return getStr("group_name");
	}
	
	public M setTaskId(java.lang.Long taskId) {
		set("task_id", taskId);
		return (M)this;
	}
	
	public java.lang.Long getTaskId() {
		return getLong("task_id");
	}
	
	public M setTaskName(java.lang.String taskName) {
		set("task_name", taskName);
		return (M)this;
	}
	
	public java.lang.String getTaskName() {
		return getStr("task_name");
	}
	
	public M setModel(java.lang.String model) {
		set("model", model);
		return (M)this;
	}
	
	public java.lang.String getModel() {
		return getStr("model");
	}
	
	public M setSystemPrompt(java.lang.String systemPrompt) {
		set("system_prompt", systemPrompt);
		return (M)this;
	}
	
	public java.lang.String getSystemPrompt() {
		return getStr("system_prompt");
	}
	
	public M setMessages(java.lang.String messages) {
		set("messages", messages);
		return (M)this;
	}
	
	public java.lang.String getMessages() {
		return getStr("messages");
	}
	
	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	public M setUsage(java.lang.String usage) {
		set("usage", usage);
		return (M)this;
	}
	
	public java.lang.String getUsage() {
		return getStr("usage");
	}
	
	public M setProvider(java.lang.String provider) {
		set("provider", provider);
		return (M)this;
	}
	
	public java.lang.String getProvider() {
		return getStr("provider");
	}
	
	public M setApiKey(java.lang.String apiKey) {
		set("api_key", apiKey);
		return (M)this;
	}
	
	public java.lang.String getApiKey() {
		return getStr("api_key");
	}
	
	public M setElapsed(java.lang.Long elapsed) {
		set("elapsed", elapsed);
		return (M)this;
	}
	
	public java.lang.Long getElapsed() {
		return getLong("elapsed");
	}
	
	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public M setCreator(java.lang.String creator) {
		set("creator", creator);
		return (M)this;
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}
	
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public M setUpdater(java.lang.String updater) {
		set("updater", updater);
		return (M)this;
	}
	
	public java.lang.String getUpdater() {
		return getStr("updater");
	}
	
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public M setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Integer getDeleted() {
		return getInt("deleted");
	}
	
	public M setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
		return (M)this;
	}
	
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}
	
}

