package com.litongjava.tio.boot.admin.dto.base;

import com.litongjava.db.activerecord.Model;
import com.litongjava.model.db.IBean;

/**
 * Generated by java-db, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTioLlmGenerateFailed<M extends BaseTioLlmGenerateFailed<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	public M setGroupId(java.lang.Long groupId) {
		set("group_id", groupId);
		return (M)this;
	}
	
	public java.lang.Long getGroupId() {
		return getLong("group_id");
	}
	
	public M setGroupName(java.lang.String groupName) {
		set("group_name", groupName);
		return (M)this;
	}
	
	public java.lang.String getGroupName() {
		return getStr("group_name");
	}
	
	public M setTaskId(java.lang.Long taskId) {
		set("task_id", taskId);
		return (M)this;
	}
	
	public java.lang.Long getTaskId() {
		return getLong("task_id");
	}
	
	public M setTaskName(java.lang.String taskName) {
		set("task_name", taskName);
		return (M)this;
	}
	
	public java.lang.String getTaskName() {
		return getStr("task_name");
	}
	
	public M setProvider(java.lang.String provider) {
		set("provider", provider);
		return (M)this;
	}
	
	public java.lang.String getProvider() {
		return getStr("provider");
	}
	
	public M setRequestUrl(java.lang.String requestUrl) {
		set("request_url", requestUrl);
		return (M)this;
	}
	
	public java.lang.String getRequestUrl() {
		return getStr("request_url");
	}
	
	public M setRequestBody(java.lang.String requestBody) {
		set("request_body", requestBody);
		return (M)this;
	}
	
	public java.lang.String getRequestBody() {
		return getStr("request_body");
	}
	
	public M setResponseCode(java.lang.Integer responseCode) {
		set("response_code", responseCode);
		return (M)this;
	}
	
	public java.lang.Integer getResponseCode() {
		return getInt("response_code");
	}
	
	public M setResponseBody(java.lang.String responseBody) {
		set("response_body", responseBody);
		return (M)this;
	}
	
	public java.lang.String getResponseBody() {
		return getStr("response_body");
	}
	
	public M setException(java.lang.String exception) {
		set("exception", exception);
		return (M)this;
	}
	
	public java.lang.String getException() {
		return getStr("exception");
	}
	
	public M setApiKey(java.lang.String apiKey) {
		set("api_key", apiKey);
		return (M)this;
	}
	
	public java.lang.String getApiKey() {
		return getStr("api_key");
	}
	
	public M setElapsed(java.lang.Long elapsed) {
		set("elapsed", elapsed);
		return (M)this;
	}
	
	public java.lang.Long getElapsed() {
		return getLong("elapsed");
	}
	
	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public M setCreator(java.lang.String creator) {
		set("creator", creator);
		return (M)this;
	}
	
	public java.lang.String getCreator() {
		return getStr("creator");
	}
	
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return getDate("create_time");
	}
	
	public M setUpdater(java.lang.String updater) {
		set("updater", updater);
		return (M)this;
	}
	
	public java.lang.String getUpdater() {
		return getStr("updater");
	}
	
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return getDate("update_time");
	}
	
	public M setDeleted(java.lang.Integer deleted) {
		set("deleted", deleted);
		return (M)this;
	}
	
	public java.lang.Integer getDeleted() {
		return getInt("deleted");
	}
	
	public M setTenantId(java.lang.Long tenantId) {
		set("tenant_id", tenantId);
		return (M)this;
	}
	
	public java.lang.Long getTenantId() {
		return getLong("tenant_id");
	}
	
}

